/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 16 21:27:20 GMT 2021
 */

package TestCaseCoverage.TCG_PaperExample;

import org.junit.Test;
import static org.junit.Assert.*;
import TestCaseCoverage.TCG_PaperExample.TCG_PaperExample_8bits;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TCG_PaperExample_8bits_ESTest extends TCG_PaperExample_8bits_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = TCG_PaperExample_8bits.separateBits_8(66);
      assertEquals(192, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = TCG_PaperExample_8bits.separateBits_8(127);
      assertEquals(254, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = TCG_PaperExample_8bits.separateBits_8((-128));
      assertEquals(255, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = TCG_PaperExample_8bits.separateBits_8((-5));
      assertEquals(255, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = TCG_PaperExample_8bits.separateBits_8(255);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = TCG_PaperExample_8bits.separateBits_8((-395));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TCG_PaperExample_8bits tCG_PaperExample_8bits0 = new TCG_PaperExample_8bits();
      assertNotNull(tCG_PaperExample_8bits0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[5];
      TCG_PaperExample_8bits.main(stringArray0);
      assertEquals(5, stringArray0.length);
  }
}
