/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 16 20:00:16 GMT 2021
 */

package TestCaseCoverage.TCG_PaperExample;

import org.junit.Test;
import static org.junit.Assert.*;
import TestCaseCoverage.TCG_PaperExample.TCG_PaperExample_4bits;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TCG_PaperExample_4bits_ESTest extends TCG_PaperExample_4bits_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TCG_PaperExample_4bits.separateBits_4(7);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TCG_PaperExample_4bits.separateBits_4((-8));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TCG_PaperExample_4bits.separateBits_4(2);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TCG_PaperExample_4bits.separateBits_4(4);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TCG_PaperExample_4bits.separateBits_4(8);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TCG_PaperExample_4bits.separateBits_4((-30));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TCG_PaperExample_4bits tCG_PaperExample_4bits0 = new TCG_PaperExample_4bits();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[6];
      TCG_PaperExample_4bits.main(stringArray0);
      assertEquals(6, stringArray0.length);
  }
}
